### ISSUE TITLE
phone number could not be VALIDATING EXITING 

### ISSUE THREAD

**Issue by d3athcod3** [Konstantinos-Papanagnou/PhoneInformationTracer#1]
after I use python3 PhoneInformationTracer.py -i <phone number>

It show me Phone number could not be VALIDATING EXITING

**Comment by Konstantinos-Papanagnou** [comment]
Did you specify the phone number you are searching for ?
In case you did, you might need to edit the +XX country code with -cc. Default country code is set to +30 (GR)

**Comment by Konstantinos-Papanagnou** [comment]
Did my answer resolve the issue? If so let me know to close the thread.

Note that the thread will be marked as resolved in 2 weeks of inactivity automatically.

Best regards,
Konstantinos Pap
